version: "3.7"

services:
  
  mongodb:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongodb-data:/data/db
    ports:
      - 27017:27017

  api:
    build: ./
    container_name: agenda-api
    volumes:
      - ./:/app
    ports:
      - 5000:5000
    depends_on:
      - mongodb

volumes:
  mongodb-data:
