version: "4.0.0"

services:

  mongodb:
    image: mongo:6.0
    container_name: agenda.mongo
    volumes:
      - mongodb-data:/data/db
    ports:
      - 27017:27017

  api:
    build: ./api/
    container_name: agenda.api
    environment:
      NODE_DEBUG: info
      DB_CONNECTION: 'mongodb://host.docker.internal:27017/agenda-dev'
    volumes:
      - ./api/:/app
    ports:
      - 4000:4000
    depends_on:
      - mongodb

  www:
    build: ./www/
    container_name: agenda.www
    volumes:
      - ./www/:/app
    ports:
      - 3000:3000
    depends_on:
      - mongodb
      - api

volumes:
  mongodb-data:
